apiVersion: v1
kind: Service
metadata:
  name: dashboard-management-service
spec:
  type: LoadBalancer # Expose the service externally
  selector:
    app: dashboard-management-service
  ports:
    - protocol: TCP
      port: 80 # External port accessible to users
      targetPort: 8080 # Port inside the container
